# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: release_publish
needs: Build

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }} 
      with: 
        tag_name: v${{github.run_number}}
        release_name: Release V${{github.run_number}}
        
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -DskipTests --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}      